language: node_js
node_js:
  - 12
script:
  - "npm run lint"
  - "npm run test"
services:
  - postgresql
before_script:
  - psql -c 'create database foodSelector;' -U postgres
env:
   global:
    - PGPORT=5433