language: node_js
node_js:
  - 12
script:
  - 'npm run lint'
  - 'npm run test'
addons:
  postgresql: '12'
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGPORT=5433
  - PASSWORD=fsuser
services:
  - postgresql
before_script:
  - sudo -u postgres psql -c "CREATE USER fsuser WITH PASSWORD 'fsuser'"
  - sudo -u postgres psql -c "ALTER ROLE fsuser SUPERUSER"
  - psql -f db/fs_bootstrap.sql -U fsuser -p 5433