language: node_js
node_js:
  - 12
script:
  - 'npm run lint'
  - 'npm run test'
addons:
  postgresql: '12'
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
services:
  - postgresql
before_script:
  - psql -f db/fs_bootstrap.sql -U postgres