language: node_js
node_js:
  - 12
script:
  - 'npm run lint'
addons:
  postgresql: '12'
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGPORT=5433
services:
  - postgresql
before_script:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/12/main/pg_hba.conf
  - sudo systemctl restart postgresql@12-main
  - sudo -u postgres psql -c "CREATE USER fsuser WITH PASSWORD 'fsuser'"
  - sudo -u postgres psql -c "ALTER ROLE fsuser SUPERUSER"
  - psql -f db/fs_bootstrap.sql -U fsuser -d postgres -p 5433